### ISSUE TITLE
error log don't write to custom log file

### ISSUE THREAD

**Issue by Guoxweii** [envylabs/faraday-detailed_logger#2]
error log don't be written to custom log file

the custom log:

![image](https://cloud.githubusercontent.com/assets/689550/17242367/5dbbebe6-55a9-11e6-9ba3-c4f5538b4e6d.png)

the develop log:

![image](https://cloud.githubusercontent.com/assets/689550/17242398/7d2c2216-55a9-11e6-8c3e-f95d3520d3a3.png)

can written the error info to custom log file?

**Comment by nbibler** [comment]
It _should_ be able to be written into a custom log file, yes. You can give the middleware a logger than is configured to write to a new/different file (meaning: it doesn't have to be the `Rails.logger`). That _should_ do what you're looking for ...

Can you show your Faraday connection build to see how you're initializing the middleware?

**Comment by nbibler** [comment]
Oh, I just realized that in the log you listed, you were receiving an SSL failure. That's totally different.

So, it looks like the custom log was working as expected. It contains the request INFO and DEBUG details. However, the server you were connecting to had a bad SSL certificate. Faraday (more specifically, actually, the Adapter Faraday is using) throws errors for failed SSL. Those errors are (correctly) being caught by your Rails application.

You see no response in the custom log, because no connection was successfully made and no response came back. The net-layer stopped the request at the point of the handshake failure.

**Comment by nbibler** [comment]
I've created and pushed [v2.1.0](https://github.com/envylabs/faraday-detailed_logger/releases/tag/v2.1.0). This should at least log out the error class name, message, and first backtrace line to your custom log file.
